const API_URL = 'http://localhost:3000/api';
export async function fetchProducts() { try { const res = await fetch(${API_URL}/products); if (!res.ok) throw new Error(); const data = await res.json(); return data.products || []; } catch { return []; } }
export async function fetchProduct(id) { try { const res = await fetch(${API_URL}/products/); return await res.json(); } catch { return { success: false }; } }
export async function login(email, password) { try { const res = await fetch(${API_URL}/auth/login, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); return await res.json(); } catch { return { success: false, message: 'Error de conexión' }; } }
export async function register(userData) { try { const res = await fetch(${API_URL}/auth/registro, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(userData) }); return await res.json(); } catch { return { success: false, message: 'Error de conexión' }; } }
export async function getProfile(token) { try { const res = await fetch(${API_URL}/auth/perfil, { headers: { 'Authorization': Bearer  } }); return await res.json(); } catch { return { success: false }; } }
export async function createProduct(product, token) { try { const res = await fetch(${API_URL}/products, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': Bearer  }, body: JSON.stringify(product) }); return await res.json(); } catch { return { success: false }; } }
export async function updateProduct(id, product, token) { try { const res = await fetch(${API_URL}/products/, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'Authorization': Bearer  }, body: JSON.stringify(product) }); return await res.json(); } catch { return { success: false }; } }
export async function deleteProduct(id, token) { try { const res = await fetch(${API_URL}/products/, { method: 'DELETE', headers: { 'Authorization': Bearer  } }); return await res.json(); } catch { return { success: false }; } }
export async function createOrder(order, token) { try { const res = await fetch(${API_URL}/orders, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': Bearer  }, body: JSON.stringify(order) }); return await res.json(); } catch { return { success: false }; } }
export async function getUserOrders(token) { try { const res = await fetch(${API_URL}/orders/mis-pedidos, { headers: { 'Authorization': Bearer  } }); return await res.json(); } catch { return { success: false }; } }
